#!/usr/bin/env python
VERSION_FILE_PATH = 'bagua/version.txt'
SEPARATOR = '.'
MAX_VERSION = 10

def cmd():
    import os
    os.system('python setup.py sdist upload')
    os.system('say OK')

def get_version_list():
    f = open(VERSION_FILE_PATH)
    s = f.read()
    s = '0.0.0' if s == '' else s
    f.close()
    return s.split(SEPARATOR)

def write_version(version):
    f = open(VERSION_FILE_PATH, 'w')
    f.write(version)
    f.close()
    print 'version :', version

def add_version(ver_list):
    rlist = []
    mod = 1
    for x in ver_list[::-1]:
        x = int(x)
        x += mod
        mod = x // MAX_VERSION
        x %= MAX_VERSION
        x = str(x)
        rlist.append(x)
    return rlist[::-1]

def main():
    ver_list = get_version_list()
    ver_list = add_version(ver_list)
    write_version(SEPARATOR.join(ver_list))

if __name__ == '__main__':
    main()
    cmd()