#!/usr/bin/env python
#coding:utf-8

"""BaGua

Usage:
  bagua
  bagua <cheatsheet>
  bagua -r
  bagua -s <keyword>
  bagua -v 

太极八卦

Examples:
  To look up 'tar':
  cheat tar
  
  To create or edit the cheatsheet for 'foo':
  cheat -e foo

Options:
  -r --random       卜一卦
  -s --search       Search cheatsheets for <keyword>
  -v --version      Print the version number
"""

# require the dependencies
from bagua import *
from docopt import docopt

if __name__ == '__main__':
	options = docopt(__doc__, version='BaGua 0.0.1')

	if options["--random"]:
		print shake_gua64()
	elif options["--search"]:
		print("search :", options['<keyword>'])
	elif options["<cheatsheet>"] is None:
		print shake_gua64()
	else:
		show(int(options["<cheatsheet>"]))
